# ===== ???????? ????????? =====
spring.application.name=kwizi
server.port=8250

# ===== ???? ?????? (PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/monolit_db
spring.datasource.username=postgres
spring.datasource.password=50432
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===== JWT =====
jwt.secret=J0dJqJ3vL2p/Jz4L5y7J1w0L9q8L2q9L4y7J1w0L9q8=
jwt.verification.expiration=3600000

# ===== Email (Gmail SMTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kwiziiverify@gmail.com
spring.mail.password=tzllgleaywmfmofq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== Swagger/OpenAPI =====
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/api/**

# ===== Kafka =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# ??????? ??????????? ??? Kafka
logging.level.org.apache.kafka=WARN
logging.level.kafka=WARN

# ?????? ?????? ??? consumer coordinator
logging.level.org.apache.kafka.clients.consumer.internals.ConsumerCoordinator=WARN
logging.level.org.apache.kafka.clients.consumer.internals.ConsumerRebalanceListenerInvoker=WARN

# Spring Kafka
logging.level.org.springframework.kafka=WARN

# ===== ???????? ????????? =====
file.storage.chat-avatar-path=uploads/avatars/chat/
file.storage.user-avatar-path=uploads/avatars/user/

# ===== ??????????? =====
logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# ===== ??????????? EMAIL =====
app.verification.email.from=noreply@example.com
app.verification.base-url=http://localhost:8250

# ===== ???????? ?????? =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB