# ===== ???????? ????????? ?????????? =====
spring.application.name=kwizi
server.port=8080

# ===== ???? ?????? (PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/monolit_db
spring.datasource.username=postgres
spring.datasource.password=50432
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===== JWT =====
jwt.secret=J0dJqJ3vL2p/Jz4L5y7J1w0L9q8L2q9L4y7J1w0L9q8=
jwt.verification.expiration=3600000

# ===== Email (Gmail SMTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kwiziiverify@gmail.com
spring.mail.password=tzllgleaywmfmofq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== ????????? ??????? =====
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.tomcat.max-threads=300
server.tomcat.accept-count=1000
server.tomcat.connection-timeout=5000

# ===== ??????????? =====
logging.file.name=logs/application.log
logging.file.path=logs
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=200MB
logging.logback.rollingpolicy.max-history=10

# WebSocket ????
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.apache.tomcat.websocket=DEBUG

# ===== Kafka (???????? ?????????) =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.auto-startup=true

# ===== Producer =====
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1  # ????????????? ?? ??????
spring.kafka.producer.linger.ms=0  # ???????? ??? ????????
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432

# ===== Consumer =====

spring.kafka.listener.group-messages.group-id=websocket-group
spring.kafka.listener.group-messages.concurrency=3

# ????????? DLQ
spring.kafka.listener.dlq.group-messages-dlq.topic=group-messages-dlq
spring.kafka.listener.dlq.group-messages-dlq.enabled=true

# ??????????? ????????
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.producer.transaction-timeout-ms=60000
spring.kafka.admin.properties.request.timeout.ms=50000
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.max-poll-records=50
spring.kafka.consumer.fetch-max-wait=500
spring.kafka.consumer.fetch-min-size=1

# ===== Retry & DLQ =====
spring.kafka.listener.ack-mode=RECORD
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.type=single

# ????????? ??????? (3 ??????? ? ?????????? 1 ???)
spring.kafka.listener.default-error-handler.enabled=true
spring.kafka.retry.topic.attempts=3
spring.kafka.retry.topic.initial-interval=1000
spring.kafka.retry.topic.multiplier=1.0
spring.kafka.retry.topic.max-interval=1000

# Dead Letter Queue (DLQ)
spring.kafka.listener.dlq-producer-property.delivery.timeout.ms=30000

# ===== ???? Kafka (?????? ??????) =====
logging.level.org.apache.kafka=WARN
logging.level.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=ERROR
logging.level.org.apache.kafka.common.metrics=ERROR
logging.level.org.apache.kafka.common.utils=ERROR
logging.level.org.apache.kafka.common.utils.AppInfoParser=ERROR
logging.level.org.apache.kafka.clients.consumer.internals=ERROR

# ????????? ????????
spring.task.scheduling.enabled=true

# ??????????? ??? ????????
logging.level.com.example.kwizi.scheduler=DEBUG

#????????? EmailService
app.verification.email.from=noreply@example.com
app.verification.base-url=http://localhost:8080


# ?????????? ???? ???????? ??? ??? ?? ???? ???????????? ???????? ?????????
file.storage.chat-avatar-path=uploads/avatars/chat/
file.storage.user-avatar-path=uploads/avatars/user/