spring.application.name=kwizi
spring.datasource.url=jdbc:postgresql://localhost:5432/monolit_db
spring.datasource.username=postgres
spring.datasource.password=50432
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=J0dJqJ3vL2p/Jz4L5y7J1w0L9q8L2q9L4y7J1w0L9q8=
jwt.verification.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kwiziiverify@gmail.com
spring.mail.password=tzllgleaywmfmofq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true